#!/bin/sh

while true; do

  # Clean up previously running apps, gracefully at first then harshly
  killall -TERM firefox-esr 2>/dev/null
  #killall -TERM chromium-browser 2>/dev/null
  killall -TERM matchbox-window-manager 2>/dev/null
  sleep 2
  killall -9 firefox-esr 2>/dev/null
  #killall -9 chromium-browser 2>/dev/null
  killall -9 matchbox-window-manager 2>/dev/null

  # Clean out existing profile information
  rm -rf /home/pi/.cache
  rm -rf /home/pi/.config
  rm -rf /home/pi/.pki
  mkdir /home/pi/.config

  # Disable DPMS / Screen blanking
  xset -dpms
  xset s off
  xset s noblank
  
  ## Start the window manager (remove "-use_cursor no" if you actually want mouse interaction)
  matchbox-window-manager -use_titlebar no -use_cursor no &

  # Hide the cursor
  unclutter &

  # Start the browser
  URL="https://homeassistant.local:8123" # In case the settings file doesn't exist
  test -f /home/pi/pi-homeasisstant-control-panel/settings.data && . /home/pi/pi-homeassistant-control-panel/settings.data
  firefox -kiosk -private-window "${URL}"
done;
